#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh"  # Loads all defined icons

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

FONT_FACE="SF Pro"
# FONT_FACE="JetBrainsMono Nerd Font"
# FONT_FACE="Hack Nerd Font"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see: https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker: https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar height=37 \
  blur_radius=0 \
  position=top \
  sticky=on \
  padding_left=10 \
  padding_right=10 \
  color=0x00000000

##### Changing Defaults #####
# We now change some default values, which are applied to all further items. For a full list of all available item properties see: https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="$FONT_FACE:Semibold:14.0"
  icon.color="$WHITE"
  icon.padding_left=5
  icon.padding_right=5
  label.color="$WHITE"
  label.font="$FONT_FACE:Semibold:14.0"
  label.padding_left=5
  label.padding_right=5
  background.color=$ITEM_BG_COLOR
  background.corner_radius=5
  background.height=26
)
sketchybar --default "${default[@]}"

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

source $ITEM_DIR/apple.sh
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh

# -- Right Side Of Notch Items --
source $ITEM_DIR/media.sh
# source $ITEM_DIR/spotify.sh

##### Adding Right Items #####

# Some items refresh on a fixed cycle, e.g. the clock runs its script once every 10s.

source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
sketchybar --trigger space_change
echo "sketchybar configuation loaded.."
